# Generated by Django 4.2.6 on 2023-10-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_full_name_alter_user_username_verifycode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='invite_code',
            field=models.CharField(blank=True, help_text='auto add active', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='value',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
